import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PageShell from "@/components/site/page-shell";
import SiteHeader from "@/components/site/header";
import SiteFooter from "@/components/site/footer";
import GlobalCyberBackground from "@/components/ui/GlobalCyberBackground";
import { ScrollProgress } from "@/components/ui/scroll-progress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden bg-[#080d12]">
        <ScrollProgress />
        <GlobalCyberBackground />
        <PageShell>
          <SiteHeader />
          <main className="pt-16 md:pt-20 relative z-10">{children}</main>
          <SiteFooter />
        </PageShell>
      </body>
    </html>
  );
}
